# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"\x06\n\x04Null\"\x13\n\x02Id\x12\r\n\x05value\x18\x01 \x01(\r\"\x94\x01\n\x07\x42ooking\x12\x14\n\x02id\x18\x01 \x01(\x0b\x32\x03.IdH\x00\x88\x01\x01\x12\x13\n\x0bhotels_name\x18\x02 \x01(\t\x12\x12\n\nstart_date\x18\x03 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\r\x12\x15\n\x08\x63omments\x18\x06 \x01(\tH\x01\x88\x01\x01\x42\x05\n\x03_idB\x0b\n\t_comments\"&\n\x0b\x42ookingList\x12\x17\n\x05items\x18\x01 \x03(\x0b\x32\x08.Booking2\x8a\x01\n\x1cProcessBookingRequestService\x12\"\n\nAddBooking\x12\x08.Booking\x1a\x08.Booking\"\x00\x12\x1d\n\nGetBooking\x12\x03.Id\x1a\x08.Booking\"\x00\x12\'\n\x0eGetAllBookings\x12\x05.Null\x1a\x0c.BookingList\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NULL._serialized_start=17
  _NULL._serialized_end=23
  _ID._serialized_start=25
  _ID._serialized_end=44
  _BOOKING._serialized_start=47
  _BOOKING._serialized_end=195
  _BOOKINGLIST._serialized_start=197
  _BOOKINGLIST._serialized_end=235
  _PROCESSBOOKINGREQUESTSERVICE._serialized_start=238
  _PROCESSBOOKINGREQUESTSERVICE._serialized_end=376
# @@protoc_insertion_point(module_scope)
