# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import builds.booking_pb2 as booking__pb2


class ProcessBookingRequestServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddBooking = channel.unary_unary(
                '/ProcessBookingRequestService/AddBooking',
                request_serializer=booking__pb2.Booking.SerializeToString,
                response_deserializer=booking__pb2.Booking.FromString,
                )
        self.GetBooking = channel.unary_unary(
                '/ProcessBookingRequestService/GetBooking',
                request_serializer=booking__pb2.Id.SerializeToString,
                response_deserializer=booking__pb2.Booking.FromString,
                )
        self.GetAllBookings = channel.unary_unary(
                '/ProcessBookingRequestService/GetAllBookings',
                request_serializer=booking__pb2.Null.SerializeToString,
                response_deserializer=booking__pb2.BookingList.FromString,
                )


class ProcessBookingRequestServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllBookings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessBookingRequestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBooking,
                    request_deserializer=booking__pb2.Booking.FromString,
                    response_serializer=booking__pb2.Booking.SerializeToString,
            ),
            'GetBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooking,
                    request_deserializer=booking__pb2.Id.FromString,
                    response_serializer=booking__pb2.Booking.SerializeToString,
            ),
            'GetAllBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllBookings,
                    request_deserializer=booking__pb2.Null.FromString,
                    response_serializer=booking__pb2.BookingList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ProcessBookingRequestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProcessBookingRequestService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProcessBookingRequestService/AddBooking',
            booking__pb2.Booking.SerializeToString,
            booking__pb2.Booking.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProcessBookingRequestService/GetBooking',
            booking__pb2.Id.SerializeToString,
            booking__pb2.Booking.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProcessBookingRequestService/GetAllBookings',
            booking__pb2.Null.SerializeToString,
            booking__pb2.BookingList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
